[IIIF-893] Update build; added Docker build
UCLALibrary/bucketeer pull request #95
Opened 2020-08-18 20:23 UTC by ksclarke

2020-08-20 18:22 UTC, DRickard commented
You seem to have duped entries for the Kakadu repo in pom.xml (lines 77-81):

```
    <!-- Git repo with Kakadu source code (ours is private; override with yours) -->
    <kakadu.git.repo>scm:git:git@github.com:uclalibrary/kakadu.git</kakadu.git.repo>

    <!-- Git repo with Kakadu source code (ours is private; override with yours) -->
    <kakadu.git.repo>scm:git:git@github.com:uclalibrary/kakadu.git</kakadu.git.repo>

```

2020-08-20 18:32 UTC, ksclarke commented
> You seem to have duped entries for the Kakadu repo in pom.xml (lines 77-81):
> 
> ```
>     <!-- Git repo with Kakadu source code (ours is private; override with yours) -->
>     <kakadu.git.repo>scm:git:git@github.com:uclalibrary/kakadu.git</kakadu.git.repo>
> 
>     <!-- Git repo with Kakadu source code (ours is private; override with yours) -->
>     <kakadu.git.repo>scm:git:git@github.com:uclalibrary/kakadu.git</kakadu.git.repo>
> ```

Doh! Thanks, removing the second one :-)

2020-08-20 18:48 UTC, DRickard commented
Minor nit, but in FesterVerticle.java, line 94:
`message.fail(500, throwable.getMessage());`
why not use `HTTP.INTERNAL_SERVER_ERROR`?

2020-08-21 01:00 UTC, markmatney requested changes
I found a few minor issues :wink: interesting learning about the platform-specific Netty optimizations.

2020-08-21 02:00 UTC, ksclarke commented on src/main/docker/Dockerfile
> +#  Removing /var/lib/apt/lists/* prevents using `apt` unless you do `apt update` first
Reduces image size and conveys the idea that this isn't a thing that's intended to be updated. New images should be minted.

2020-08-21 02:00 UTC, ksclarke commented on pom.xml
> +    </developer>
You'll be working on it  ;-)

2020-08-21 02:01 UTC, markmatney commented on src/main/docker/Dockerfile
> +#  Removing /var/lib/apt/lists/* prevents using `apt` unless you do `apt update` first
cool, I figured it was a guard

2020-08-21 02:02 UTC, markmatney commented on pom.xml
> +    </developer>
LOL :crystal_ball:

2020-08-21 02:03 UTC, ksclarke commented on src/main/java/edu/ucla/library/bucketeer/handlers/MatchingOpNotFoundHandler.java
> + * HttpServerReponse and set 404 as the response code, remembering to call <code>.end()</code> on the response.
It's more along the lines of documentation for the future, based on past troubles (this class is actually copied from Fester where I learned this lesson the hard way; I debated removing it but thought my future self would thank me for leaving it).

2020-08-21 02:08 UTC, ksclarke commented on src/main/resources/bucketeer_messages.xml
> +  <entry key="BUCKETEER-503">Resource not found: {}</entry>
I must have changed my mind about it. Removing the entry from the XML file.

2020-08-21 16:45 UTC, markmatney approved these changes

2020-08-21 22:23 UTC, DRickard approved these changes

2020-08-21 22:27 UTC, merged